const RESPONSE_STOCKS = 'stocks';
const RESPONSE_ID = 'stocks_id';
const RESPONSE_DATETIME = 'datetime';

const RESPONSE_DICT = {
    [RESPONSE_STOCKS]: [],
    [RESPONSE_ID]: '',
    [RESPONSE_DATETIME]: ''
};

const COMPANY_SYMBOL = 'symbol';
const COMPANY_SHORT_NAME = 'shortName';
const COMPANY_PRICE = 'price';
const COMPANY_CURRENCY = 'currency';
const COMPANY_SOURCE = 'source';

const COMPANY_DICT = {
    [COMPANY_SYMBOL]: '',
    [COMPANY_SHORT_NAME]: '',
    [COMPANY_PRICE]: '',
    [COMPANY_CURRENCY]: '',
    [COMPANY_SOURCE]: ''
};

const RESPONSE_ALL_KEYS = [
    RESPONSE_STOCKS, RESPONSE_ID, RESPONSE_DATETIME,
    COMPANY_SYMBOL, COMPANY_SHORT_NAME, COMPANY_PRICE, COMPANY_CURRENCY, COMPANY_SOURCE
]

module.exports = { 
    RESPONSE_STOCKS, RESPONSE_ID, RESPONSE_DATETIME,
    COMPANY_SYMBOL, COMPANY_SHORT_NAME, COMPANY_PRICE, COMPANY_CURRENCY, COMPANY_SOURCE, 
    RESPONSE_DICT, COMPANY_DICT, RESPONSE_ALL_KEYS
};