version: '3.3'

services:
  listener:
    build:
      context: ./Listener
      dockerfile: Dockerfile
    container_name: Listener
    ports:
      - "${PORT_LISTENER}:${PORT_LISTENER}"
    volumes:
      - ./Listener/src:/Listener/src
    networks:
      - back-network
    restart: unless-stopped
    environment:
      PORT_LISTENER: ${PORT_LISTENER}
      API_URL: ${API_URL}

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: API
    ports:
      - "${PORT_API}:${PORT_API}"
    volumes:
      - ./API/src:/API/src
    networks:
      - back-network
    depends_on:
      - db
      - listener
    restart: unless-stopped
    environment:
      PORT_API: ${PORT_API}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      FRONT_URL: ${FRONT_URL}

  db:
    image: postgres:latest
    container_name: Database
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - back-network
    volumes:
      - db-volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  # producer:
  #   build: 
  #     context: ./worker-service/producers
  #     dockerfile: Dockerfile
  #   networks:
  #     - back-network
  #   environment:
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - REDIS_HOST=redis

  consumer:
    build: 
      context: ./worker-service/consumers
      dockerfile: Dockerfile
    networks:
      - back-network
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
    deploy:
      replicas: 1

  redis:   # Este es el broker que simplemente duplica la imagen, como no expongo nada, no tiene asignado un puerto (no es una API por ejemplo)
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - back-network

  board:
    build: 
      context: ./worker-service/board
      dockerfile: Dockerfile
    networks:
      - back-network
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
    ports:
      - 3000:3000

networks:
  back-network:
    driver: bridge

volumes:
  db-volume:
