name: Build and Push to ECR

on:
    push:
        branches:
            - main, develop

permissions:
    id-token: write
    contents: read


env:
    ECR_REGISTRY: <your-ecr-registry>
    IMAGE_NAME: <your-image-name>

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::866733551467:role/iic2173-github-actions-ecr-workflow
            aws-region: us-east-1

        - name: Login to Amazon ECR Public
          id: login-ecr-public
          uses: aws-actions/amazon-ecr-login@v2
          with:
            registry-type: public

        - name: Build, tag, and push api to Amazon ECR Public
          env:
            REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
            REGISTRY_ALIAS: p3t1e0p3
            REPOSITORY: grupo1-api
            IMAGE_TAG: latest
            IMAGE_NAME: api
          run: docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG $IMAGE_NAME
              docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
